# Generated by Django 3.0.2 on 2020-01-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charsheet',
            old_name='character_date',
            new_name='char_date',
        ),
        migrations.RenameField(
            model_name='charsheet',
            old_name='character_name',
            new_name='char_name',
        ),
        migrations.RenameField(
            model_name='charsheet',
            old_name='character_shortbio',
            new_name='char_shortbio',
        ),
    ]
