# Generated by Django 3.0.2 on 2020-01-11 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200111_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charsheet',
            name='char_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 15, 58, 49, 164009), verbose_name='Data de Criação do Personagem'),
        ),
    ]
