# Generated by Django 2.2.9 on 2020-01-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200112_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_name', models.CharField(max_length=100)),
                ('char_level', models.IntegerField()),
                ('char_exp', models.IntegerField()),
                ('char_race', models.CharField(max_length=20)),
                ('char_class', models.CharField(max_length=30)),
                ('char_alignement', models.CharField(max_length=2)),
                ('char_size', models.CharField(max_length=1)),
                ('char_shortbio', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Charsheet',
        ),
    ]
